# Change these first
owner: JFronny # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: JfGit
    url: https://git.frohnmeyer-wds.de/
  - name: Gitea Helpdesk Issues
    url: https://git.frohnmeyer-wds.de/Johannes/Gitea-Helpdesk/issues
  - name: Gitea Helpdesk Issue
    url: https://git.frohnmeyer-wds.de/Johannes/Gitea-Helpdesk/issues/1
  - name: YouTrack
    url: https://youtrack.frohnmeyer-wds.de/form/cc0e428b-e887-4487-a90a-9e12b28ff4a4
  - name: Gitea Helpdesk
    url: https://helpdesk.frohnmeyer-wds.de/
  - name: Woodpecker
    url: https://ci.frohnmeyer-wds.de/repos/28
  - name: Pages
    url: https://pages.frohnmeyer-wds.de/JfMods/Respackopts/
  - name: Frohnmeyer-Maven
    url: https://maven.frohnmeyer-wds.de/artifacts/io/gitlab/jfronny/commons-bom/maven-metadata.xml
  - name: Matrix
    url: https://matrix.frohnmeyer-wds.de/_matrix/client/versions
  - name: Johannes
    url: https://johannes.frohnmeyer-wds.de/schule/sport/praesentation/
  - name: Lotus
    url: http://lotus.frohnmeyer-wds.de/feed.rss
  - name: Nextcloud
    url: https://nextcloud.frohnmeyer-wds.de/s/5LHM53735gsamFE
  - name: FreshRSS
    url: https://rss.frohnmeyer-wds.de/i/?a=about
  - name: S3
    url: https://s3.frohnmeyer-wds.de/pages/JfMods/Respackopts/index.html
  - name: Mail (SMTP)
    url: frohnmeyer-wds.de
    port: 25
    check: "tcp-ping"
  - name: Mail (SMTPS)
    url: frohnmeyer-wds.de
    port: 465
    check: "ssl"
  - name: Mail (IMAPS)
    url: frohnmeyer-wds.de
    port: 993
    check: "ssl"

assignees:
  - JFronny

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  actions: true
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: Uptime tracker for my services
  introMessage: This uptime tracker is powered by GitHub Actions. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
